repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: detect-private-key
#
#-   repo: https://github.com/psf/black
#    rev: 24.1.1
#    hooks:
#    -   id: black
#
#-   repo: https://github.com/PyCQA/flake8
#    rev: 7.0.0
#    hooks:
#    -   id: flake8
#        additional_dependencies: [flake8-docstrings]
#
#-   repo: https://github.com/PyCQA/pylint
#    rev: v3.0.3
#    hooks:
#    -   id: pylint
#        args: [--disable=C0111]
#
#-   repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.39.0
#    hooks:
#    -   id: markdownlint
#
#-   repo: https://github.com/zricethezav/gitleaks
#    rev: v8.18.2
#    hooks:
#    -   id: gitleaks
