name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check .editorconfig
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install pylint black flake8 editorconfig-checker
          npm install -g markdownlint-cli
          editorconfig-checker
    
      - name: Analysing the code with pylint
          run: |
            find . -name '*.py' | xargs pylint
            black --check --diff .
            flake8 .
      - name: Check markdown files
          run: |
            markdownlint-cli .
